platform :ios, '9.0'

source 'https://github.com/cocoapods/specs'

# flag makes all dependencies build as frameworks
use_frameworks!

# flag to ignore warnings from all dependencies
inhibit_all_warnings!

def shared_pods
  pod 'AlamofireHandlers', :path => '../'
end

def testing_pods
    pod 'Quick', '~> 1.3.0'
    pod 'Nimble', '~> 7.3.0'
    pod 'RxBlocking', '~> 4.4.0'
end

target 'AlamofireHandlers_Example' do
  shared_pods
end

target 'AlamofireHandlers_Tests' do
  inherit! :search_paths
  use_frameworks!
  
  shared_pods
  testing_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end
