use_frameworks!
platform :ios, '9.0'

def testing_pods
    pod 'Quick'
    pod 'Nimble'
    pod 'RxSwift'
    pod 'RxBlocking'
end

target 'AlamofireHandlers_Example' do
  pod 'AlamofireHandlers', :path => '../'

  target 'AlamofireHandlers_Tests' do
    inherit! :search_paths
    testing_pods

  end
end
